name: Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature! Please fill out the information below to help us understand your request.
    - type: textarea
      id: use-case
      attributes:
          label: Use Case
          description: Describe the problem or limitation you're facing that this feature would solve.
          placeholder: Currently I'm unable to... This feature would enable me to...
      validations:
          required: true
    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: If you have an idea of how this could be implemented, please share it here.
          placeholder: This could work by...
      validations:
          required: false
    - type: dropdown
      id: priority
      attributes:
        label: How important is this feature to you?
        description: Select the priority level for this feature request.
        options:
          - Low (Nice to have)
          - Medium (Would improve workflow)
          - High (Significantly impacts my usage)
      validations:
        required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What version of our Package are you currently using?
          placeholder: 2.1.6
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
        label: Laravel Version
        description: What version of Laravel are you using?
        placeholder: 12.0.0
      validations:
        required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Have you considered any alternative solutions or workarounds?
          placeholder: I've tried to work around this by...
      validations:
          required: false
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or examples about the feature request here.
      validations:
          required: false
